"""initial migration

Revision ID: 471ad20aee59
Revises: None
Create Date: 2014-11-10 02:02:01.564308

"""

# revision identifiers, used by Alembic.
revision = '471ad20aee59'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
